### ISSUE TITLE
Question about Prometheus in a shared cluster

### ISSUE THREAD

**Issue by mitchellmaler** [prometheus-operator/prometheus-operator#1336]
Hello, 

We are looking at using a shared k8s environment as trying to plan how multiple teams will manage their prometheus envs. Is it safe to say that we would have to deploy the operator in each namespace which then deploys their own instance of prometheus and alert manager?

We are also having some difficulty knowing how each team will configure each instance. It looks as you have to use a secret for the alert manager rules but we want teams to just be able to redeploy a config map with new rules as needed which is then added to alert manager. I went down the path of trying to use helm to setup the secret but it is difficult to generate a dynamic yml file then base64 inject it into a secret.

**Comment by brancz** [comment]
With #1333 we are finishing something that we've been working on for some time, which is the ability to share 1 prometheus servers in either combination of either 1 to 1 mapping of namespace to Prometheus server or n to 1, while retaining the ability to configure what's important for the users: how to retrieve metrics (ServiceMonitors) and what to do with metrics (Rules). This allows an infrastructure team to manage the Prometheus servers and tune them as they like while users get sort of a SaaS offering experience.

Regarding alertmanager configuration, this mostly depends on your organizations structure. A lot of people have a static mapping of 1-to-1 for namespace to team, I would need to know more how you use Kubernetes in order to make a more concrete suggestion.

Lastly for generating the Secret, I encourage you to have a look at [jsonnet](https://jsonnet.org/) + [ksonnet-lib](https://github.com/ksonnet/ksonnet-lib/). You can generate the secret simply with this code from the content of the `alertmanagerConfig` variable:

https://github.com/coreos/prometheus-operator/blob/3a4da27c68832956d066956150fea173e40761a9/contrib/kube-prometheus/jsonnet/kube-prometheus/alertmanager/alertmanager.libsonnet#L25-L28

**Comment by mitchellmaler** [comment]
@brancz That sounds awesome. Being able to have a single prometheus with rules and service monitors in different namespaces. Do you know when this will be released and available?

**Comment by mxinden** [comment]
@mitchellmaler We are planning to release this with Prometheus Operator `v0.20.0`. @brancz just merged the PR.

Missing pieces:
- Documentation
- Migration path
...

**Comment by brancz** [comment]
Just to set expectations, there is no planned timeline, it’s done when it’s done. Problems can pop up at any time that can indefinitely defer a release.

That said the major features that we were aiming for in this release have been merged :) now it’s validating further that everything works as expected and the thing Max has already mentioned.

**Comment by mitchellmaler** [comment]
@brancz That makes perfect sense! Just excited to give it a try! 👍

**Comment by simonpasquier** [comment]
Regarding Alertmanager, we now have the `AlertmanagerConfig` CRD allowing teams to provision their own routing tree for alerts. For service monitors and rules, everything's already in place to have a shared Prometheus monitoring several independent namespaces. I'm going to close this, feel free to open specific issues if you think that there are still gaps.
