### ISSUE TITLE
Wrong prometheus data source host in grafana

### ISSUE THREAD

**Issue by n-sviridenko** [prometheus-operator/prometheus-operator#1419]
**What did you do?**
Default installation

**What did you expect to see?**
Working grafana dashboard

**What did you see instead? Under which circumstances?**
Wrong hostname in the prometheus data source config

**Environment**
Doesn't matter

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T20:00:41Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

kubeadm on ubuntu

---

Possible resolution:

Define the data source host: (https://github.com/coreos/prometheus-operator/blob/v0.19.0/helm/grafana/templates/dashboards-configmap.yaml#L27) the same way as the service host (https://github.com/coreos/prometheus-operator/blob/v0.19.0/helm/prometheus/templates/_helpers.tpl#L14-L25)

**Comment by vielktus** [comment]
I'm running into this issue too. My workaround is use `Direct` and change datasource URL to ingress to connect to datasource from grafana homepage instead of `Proxy`

**Comment by n-sviridenko** [comment]
@vielktus I think better is to update the chart :)

**Comment by sneko** [comment]
@n-sviridenko @vielktus Hi everyone :)

I don't know if it's related but it was not working for me too. Grafana was trying to access by default to "http://kube-prometheus-prometheus:9090" as a proxy.

I noticed that behind this service "kube-prometheus-prometheus" has no pod bound. While investigating I saw that the labels selector was looking for:
```
    "selector": {
      "app": "prometheus",
      "prometheus": "kube-prometheus"
    },
```

But that my Prometheus pod has the following labels:
```
    "labels": {
      "app": "prometheus",
      "controller-revision-hash": "prometheus-kube-prometheus-prometheus-84c4b54996",
      "prometheus": "kube-prometheus-prometheus",
      "statefulset.kubernetes.io/pod-name": "prometheus-kube-prometheus-prometheus-0"
    },
```

As you can see they can't match... So I replaced the prometheus label of the service selector by "      "kube-prometheus-prometheus" and now it works well!

I don't understand why it happened since the both following files lines seems to set the same .prometheus property:
https://github.com/coreos/prometheus-operator/blob/v0.19.0/helm/prometheus/templates/service.yaml#L42
https://github.com/coreos/prometheus-operator/blob/v0.19.0/helm/prometheus/templates/prometheus.yaml#L8

I hope it could help someone 😄 

I was willing to make a PR but since I don't understand why they are different... ^^

**Comment by sneko** [comment]
Oh, it seems related to #1412

**Comment by ntfrnzn** [comment]
The configuration of the prometheus service name https://github.com/coreos/prometheus-operator/blob/v0.19.0/helm/prometheus/templates/service.yaml#L17 defaults to the templated `prometheus.fullname` which "usually" joins the release name with the suffix "-prometheus"
https://github.com/coreos/prometheus-operator/blob/v0.19.0/helm/prometheus/templates/_helpers.tpl#L22 

https://github.com/coreos/prometheus-operator/pull/1413 seems incorrect to me (or at least, breaks my installation)  Perhaps it is better to use `prometheus.fullnameOverride`? Is that what others are doing?

**Comment by brancz** [comment]
cc @gianrubio

**Comment by gianrubio** [comment]
@brancz the changes has been applied to the helm chart, however the CI is failing before we sync the files to s3. Do you mind to fix the CI?

**Comment by mtaylor91** [comment]
I'm also running into this issue - in my case it seems to be caused by installing the prometheus-operator chart as a dependency of another chart; this changes the release name and causes grafana to attempt to connect to prometheus at the release name for the dependent chart.

**Comment by ntfrnzn** [comment]
I only come back to this problem every couple weeks when I try to upgrade the installation process to the latest versions. With helm chart versions coreos/prometheus-operator:0.0.26 and coreos/kube-prometheus:0.0.89 I'm still seeing the mismatch in grafana datasource names. I really do not want to fork these charts for my own use & would prefer to receive all the upstream improvements. Maybe there are proper value overrides?

fill in the blanks, 
```
   helm install --set simply.configure=these-values coreos/prometheus-operator
   helm install --set and.now=it-all-works coreos/kube-prometheus
```

**Comment by rgardam** [comment]
I have created a PR -> https://github.com/coreos/prometheus-operator/pull/1566
This enables the ability to override the service name for prometheus
