### ISSUE TITLE
Alertmanager usage tutorial (with helm)

### ISSUE THREAD

**Issue by ksemaev** [prometheus-operator/prometheus-operator#1883]
**What did you do?**
Tried to add rules

**What did you expect to see?**
Some reasonable guide

**What did you see instead? Under which circumstances?**
Hardcoded configs, split all across repository.

TY for creating one common repositiry for prometheus. I was able to read, understand and link together all that wonderful configs, but one: alertmanager. It creates statefulset (and I don't see any values for configuring it, there is even no template for it in any directory), and then there's absolutely no understanging on how to use it.
Could you please provide any explanation on how to add/edit alertmanager rules.

**Comment by ajfriesen** [comment]
Agree.
I am trying to understand how to add alert rules to the helm setup.
Hopefully I will find it soon.

**Comment by vsliouniaev** [comment]
@caiobegotti I think part of the slowness to respond to this issue is that the helm charts have been in the process of being migrated to https://github.com/helm/charts. This is now complete, could you see if this fixes your issue. Please be aware, there are significant changes to the way the chart is deployed between here and helm/charts.

The alertmanager configuration in this setup can be provided here: https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml#L66

**Comment by paulfantom** [comment]
All helm-related issues should be targetted towards https://github.com/prometheus-community/helm-charts as this is were the development of those charts take place. Please open a new issue in the said repository if you feel this problem is still present.
