### ISSUE TITLE
Bug Report: crd-apigroup flag doesn't work in the v0.26.0

### ISSUE THREAD

**Issue by anandsinghkunwar** [prometheus-operator/prometheus-operator#2238]
**What did you do?**
Use `--crd-apigroup=test-monitoring.coreos.com` with a custom API group

**What did you expect to see?**
Expect it to watch the new API group instead of the default one

**What did you see instead? Under which circumstances?**

**Environment**

* Prometheus Operator version:
v0.26.0

* Kubernetes version information:
```
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Prometheus Operator Logs:
In version 0.26.0
```
ts=2018-12-18T17:34:59.987778434Z caller=main.go:165 msg="Starting Prometheus Operator version '0.26.0'."
level=info ts=2018-12-18T17:35:00.011685443Z caller=operator.go:209 component=alertmanageroperator msg="connection established" cluster-version=v1.10.3
level=info ts=2018-12-18T17:35:00.015433094Z caller=operator.go:377 component=prometheusoperator msg="connection established" cluster-version=v1.10.3
level=info ts=2018-12-18T17:35:00.112100171Z caller=operator.go:631 component=alertmanageroperator msg="CRD updated" crd=Alertmanager
level=info ts=2018-12-18T17:35:00.136427173Z caller=operator.go:1427 component=prometheusoperator msg="CRD updated" crd=Prometheus
level=info ts=2018-12-18T17:35:00.151121508Z caller=operator.go:1427 component=prometheusoperator msg="CRD updated" crd=ServiceMonitor
level=info ts=2018-12-18T17:35:00.163643757Z caller=operator.go:1427 component=prometheusoperator msg="CRD updated" crd=PrometheusRule
ts=2018-12-18T17:35:03.113982058Z caller=main.go:253 msg="Unhandled error received. Exiting..." err="waiting for Alertmanager crd failed: timed out waiting for Custom Resource: failed to list CRD: alertmanagers.
monitoring.coreos.com is forbidden: User \"system:serviceaccount:test-monitoring:test-monitoring-prometheus-operator\" cannot list alertmanagers.monitoring.coreos.com at the cluster scope"
```
In the above log it should have been `alertmanagers.test-monitoring.coreos.com` instead of `alertmanagers.monitoring.coreos.com`.
 
In version v0.25.0 it seems to work
```
ts=2018-12-18T17:40:05.626316116Z caller=main.go:165 msg="Starting Prometheus Operator version '0.25.0'."
level=info ts=2018-12-18T17:40:05.675101571Z caller=operator.go:371 component=prometheusoperator msg="connection established" cluster-version=v1.10.3
level=info ts=2018-12-18T17:40:05.678287433Z caller=operator.go:209 component=alertmanageroperator msg="connection established" cluster-version=v1.10.3
level=info ts=2018-12-18T17:40:05.81445132Z caller=operator.go:627 component=alertmanageroperator msg="CRD updated" crd=Alertmanager
level=info ts=2018-12-18T17:40:05.871398564Z caller=operator.go:1417 component=prometheusoperator msg="CRD updated" crd=Prometheus
level=info ts=2018-12-18T17:40:05.883944736Z caller=operator.go:1417 component=prometheusoperator msg="CRD updated" crd=ServiceMonitor
level=info ts=2018-12-18T17:40:05.897371716Z caller=operator.go:1417 component=prometheusoperator msg="CRD updated" crd=PrometheusRule
level=info ts=2018-12-18T17:40:08.826665682Z caller=operator.go:225 component=alertmanageroperator msg="CRD API endpoints ready"
level=info ts=2018-12-18T17:40:09.027151092Z caller=operator.go:180 component=alertmanageroperator msg="successfully synced all caches"
level=info ts=2018-12-18T17:40:09.027376673Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=test-monitoring/test-monitoring-prometheus-alertmanager
level=info ts=2018-12-18T17:40:09.054331718Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=test-monitoring/test-monitoring-prometheus-alertmanager
level=info ts=2018-12-18T17:40:09.065334661Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=test-monitoring/test-monitoring-prometheus-alertmanager
level=info ts=2018-12-18T17:40:14.929313306Z caller=operator.go:387 component=prometheusoperator msg="CRD API endpoints ready"
level=info ts=2018-12-18T17:40:15.630402049Z caller=operator.go:322 component=prometheusoperator msg="successfully synced all caches"
level=info ts=2018-12-18T17:40:15.630626995Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=test-monitoring/test-monitoring-prometheus-prometheus
level=info ts=2018-12-18T17:40:15.705755289Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=test-monitoring/test-monitoring-prometheus-prometheus
level=info ts=2018-12-18T17:40:15.755423806Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=test-monitoring/test-monitoring-prometheus-prometheus
```

**Comment by brancz** [comment]
This was an experimental flag, that we removed as it didn't seem to be necessary, why do you need this?

**Comment by anandsinghkunwar** [comment]
We use this flag in our setup as we have multiple prometheus operators deployed.

**Comment by holmsten** [comment]
The stable/prometheus-operator helm chart make use of this flag, see [#10092](https://github.com/helm/charts/pull/10092) (@anandsinghkunwar was the one who wrote it).

**Comment by anandsinghkunwar** [comment]
@brancz @holmsten Should we remove it from the helm chart as well in that case?

**Comment by brancz** [comment]
I'd say let's remove it, as it's too much against the way Kubernetes works.

**Comment by anandsinghkunwar** [comment]
I'm of the opinion to keep it, I feel other folks might be using it and haven't yet updated their operator hence don't realise it yet.

**Comment by brancz** [comment]
If you feel strongly I'm also ok with adding it back, it will take some effort though.

**Comment by anandsinghkunwar** [comment]
Thanks for that @brancz. I will be glad to help out in any way.

**Comment by holmsten** [comment]
@brancz Out of curiosity.. what are the technical difficulties / "against the way Kubernetes works" in letting the user decide crd api group?

**Comment by brancz** [comment]
Sorry for not being specific enough. The generators to generate Kubernetes client code (as in our api/client packages) requires a hardcoded API group. Before we used those generators we hand wrote these, but there were a number of bugs so we decided to not rewrite all of this and just use what all of Kubernetes world uses.

**Comment by Havilland** [comment]
I would like to know the status of this issue. 

I just tried to run the prometheus-operator v0.28.0 and the crd-apigroup flag is ignored and tries to query monitoring.coreos.com.

**Comment by brancz** [comment]
I apologize for that, we always treated it as such as we knew it was outside of the available features in the generated clients for Kubernetes. If we can find a way to make this work with Kubernetes client generation I'm fine with re-introducing, but not using the client generation is out of question as it solved severe bugs in connection handling that made the Prometheus Operator defunct if there are ever connection problems between it and the Kubernetes API, which must be tolerable but it doesn't make sense for us to re-implement all of Kubernetes apimachinery. As I said if we can accommodate for this next to client generation, I'm happy with re-introducing. In particular it may be possible to set the GKV in the rest client on this [struct](https://github.com/coreos/prometheus-operator/blob/master/pkg/client/versioned/typed/monitoring/v1/monitoring_client.go#L35-L37). Similar to how it is done in [here](https://github.com/coreos/prometheus-operator/blob/master/pkg/client/versioned/typed/monitoring/v1/monitoring_client.go#L83-L94). If we put that configuration logic into a separate file, then it would be unaffected by client generation, so that would be worth a shot I think. If anyone wants to attempt that, feel free to.

**Comment by YonatanKiron** [comment]
Hey guys, any news on bringing this back?
I'm trying for a few days now, but seems like there is a golang "magic" that keep bringing this issue.
The only working option I found is changing the [code](https://github.com/coreos/prometheus-operator/blob/master/pkg/apis/monitoring/register.go#L18).
I also tried to override this value and [this one](https://github.com/coreos/prometheus-operator/blob/master/pkg/apis/monitoring/v1/register.go#L26) but no luck there..
So if you have any other idea that may be help me with this fix I will be happy :) 

We are using this flag since we have multiple prometheus, for monitoring (Multiple environments) **and** for data analyzing. Also, we want to have backup policy for our monitoring infrastructure in case we have issues / Upgrading to new version.

I thought maybe we can use an environment variable for setting this value (Just for k8s) and this will be 100x easier fix :) @brancz WDYT?

**Comment by brancz** [comment]
Unfortunately because we kind of have to use the generators I don't see a good way of doing this, other than integrating functionality like this into the generators.

> We are using this flag since we have multiple prometheus, for monitoring (Multiple environments) and for data analyzing. Also, we want to have backup policy for our monitoring infrastructure in case we have issues / Upgrading to new version.

I'm curious how you do this generally with Kubernetes today, as Kubernetes itself doesn't allow you to do things like this.

**Comment by YonatanKiron** [comment]
> Unfortunately because we kind of have to use the generators I don't see a good way of doing this, other than integrating functionality like this into the generators.

Yah, I figure it out in the hard way :( 


> I'm curious how you do this generally with Kubernetes today, as Kubernetes itself doesn't allow you to do things like this.

First, we have multiple clusters
Second, we are running prometheus `0.25` just because it does have crdgroup flag.

We will probably run multiple prometheuses and will try to divide them by labels and using the same CRDs.
I will update here on the results, and will open a PR that will remove this flag and document how to remove the flag for those who are still using it

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time. Since then we made significant changes to prometheus-operator. If you think this issue is still valid, please reopen it.
