### ISSUE TITLE
Prometheus Operator requires `get` verb on `namespaces` resource

### ISSUE THREAD

**Issue by madorn** [prometheus-operator/prometheus-operator#2752]
When Prometheus Operator deployed and watching its own or single namespace, `get` verb on `namespaces` resource is required. If the Service Account associated with Prom Operator does not have this permission, see the following in logs:

`E0905 15:46:42.284549       1 reflector.go:125] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:455: Failed to list *v1.Namespace: namespaces "promtest" is forbidden: User "system:serviceaccount:help:prometheus-operator" cannot get resource "namespaces" in API group "" in the namespace "promtest"`

Per @brancz, Prometheus Operator shouldn't need access to `namespaces` resource when watching single or own namespace.

**Comment by brancz** [comment]
This is still applicable.

**Comment by paulfantom** [comment]
RBAC is set outside of prometheus-operator codebase and examples show now a necessary operations: https://github.com/prometheus-operator/prometheus-operator/blob/master/example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml#L64-L71

If you think this issue is still valid, please reopen it.
