### ISSUE TITLE
promethesrules crd is failing

### ISSUE THREAD

**Issue by gowrisankar22** [prometheus-operator/prometheus-operator#2935]
Hello Colleagues,

While applying prometheusrules crd it fails.

kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml

The CustomResourceDefinition "prometheusrules.monitoring.coreos.com" is invalid: spec.validation.openAPIV3Schema.properties[metadata]: Forbidden: must not specify anything other than name and generateName, but metadata is implicitly specified

**Comment by brancz** [comment]
cc @pgier

**Comment by pgier** [comment]
@gowrisankar22 we saw a similar issue in https://github.com/coreos/kube-prometheus/issues/341 due to a mismatch between using prometheus-operator v0.34.0 and applying the updated CRDs from master.  Can you confirm that you are using prometheus-operator v0.34.0?  You should be able to resolve the issue by using the `master` tag of the prometheus-operator image.  You may need to delete the prometheusrules crd before applying it again.

**Comment by gowrisankar22** [comment]
Yes, it works. But this is not idempotent. why is that ?

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time. Since then we made significant changes to prometheus-operator. If you think this issue is still valid, please reopen it.
