### ISSUE TITLE
Plans to move the Helm chart back?

### ISSUE THREAD

**Issue by ryaneorth** [prometheus-operator/prometheus-operator#3161]
Given the deprecation timeline of the central helm repository (https://github.com/helm/charts#deprecation-timeline) are there plans to move the prometheus-operator Helm chart back to this repository or some other de-centralized Helm repository?

**Comment by brancz** [comment]
We're definitely not going to move it back into this repository. That said we've discussed a number of times to move this and the kube-prometheus repo out of the coreos org into a more neutral org. I could see the helm chart moving into that org as well. That said, my personal condition for this would be the renaming of the chart to be the kube-prometheus chart, because prometheus-operator is _only_ the kubernetes controllers, and kube-prometheus represents the entire setup.

**Comment by ryaneorth** [comment]
That makes sense. Thank you for your response @brancz ! Is there any timeline for this?

**Comment by brancz** [comment]
Currently trying to figure out who currently owns the [kube-prometheus](https://github.com/kube-prometheus) org. Basically once we've agreed on a suitable org, I'm all for just doing it :)

**Comment by sc250024** [comment]
Totally for this. The Bitnami Prometheus operator chart is well-maintained, but lacks many of the features already built-in to the community version.

**Comment by brancz** [comment]
Still some details to be figured out and being discussed. https://github.com/coreos/prometheus-operator/issues/3273

**Comment by paulfantom** [comment]
Helm chart was moved to https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack and is now community maintained.
