### ISSUE TITLE
Maintain a helm chart

### ISSUE THREAD

**Issue by izelnakri** [prometheus-operator/prometheus-operator#3169]
Since the introduction of ```kubectl -k``` and ```helm 3```, it is now possible to version control helm charts and run kustomize over the output of an helm chart without installing additional software. This gives developers 100% control over their manifest and provides an easy way to automate their workflow using the native/and standard software.

Having `prometheus-operator` chart as 'community-supported' creates many roadblocks for the adoption of this project. Certain CRDS are missing in the community supported helm chart such as `GrafanaDashboard`,  `AlertManagerRule`, `GrafanaChart` that could sync with Grafana and Prometheus AlertManager, and alows further automation of essential cluster state.

In my opinion this is an essential part of administering a kubernetes cluster and resorting to jsonnet instead of the now-default `kubectl -k` would be a disservice to many developers. Helm 3 allows for custom repositories, so I believe there is no reason not to maintain a helm chart that people can use easily. People can use jsonnet over the `helm output` so a helm chart has to be maintained in this repository in my opinion:

https://helm.sh/docs/topics/chart_repository/

**Comment by brancz** [comment]
None of the maintainers use helm and we used to have a helm chart as part of this repo and it certainly did not work out well, which is exactly why it was removed. I'm not opposed to have a separate repo for it, as mentioned here: https://github.com/coreos/prometheus-operator/issues/3161, but we will not be having one as part of this repo again. It would give a false perception of the maintainers properly taking care of it, which would not be the case.

**Comment by izelnakri** [comment]
Could you expand on why it did not work well? A lot happened & happening on the helm development side of things. Today I found the best way to deploy any 3rd party k8s project is to helm output their chart and run kustomization over it when values.yaml falls short. This approach works with jsonnet as well meanwhile the current suggested jsonnet customization doesnt work well with kustomize(which is default/standard now) and is custom.

**Comment by lilic** [comment]
> Could you expand on why it did not work well?

As Frederic said, we do not use helm or that helm chart, and we cannot maintain it or provide support for it when users open issues about it.

> Certain CRDS are missing in the community supported helm chart such as GrafanaDashboard, AlertManagerRule, GrafanaChart that could sync with Grafana and Prometheus AlertManager, and alows further automation of essential cluster state.

We are not preventing those who maintain or use that chart to add those things in the upstream community supported chart. Not sure what the difference between it being here and upstream?

**Comment by izelnakri** [comment]
Hi @lilic, I would still appreciate an explanation on why having a chart in this repo did not work well and is a bad idea.

" Why are you or someone else not adding those things in the chart upstream? Not sure what the difference between it being here or in the upstream?" -> if the Chart configurations were in this repo than it is much easier to create a automated release process where chart would always be kept up to date and not dependent on the outdated helm stable PR request process. Also it serves as another way of documentation of the system for developers to who would like to contribute or simply want to understand the code as an introduction or progression, other than reading the source code.

**Comment by brancz** [comment]
Because none of the maintainers used and use helm and helm contributions were always sporadic and no one ever truly took maintainership of them they just naturally decayed, and people opened issues against the repo for something the maintainers had no reasonable way to respond that would actually be satisfactory.

Again, we're super happy to give someone that responsibility, even in a blessed space, but not within this repository.

**Comment by vsliouniaev** [comment]
@izelnakri Are those additional CRDs you mentioned in-use somewhere?

**Comment by haf** [comment]
Instead of having a Helm chart, how about having plain kubernetes manifests in this repo? That way, people can [c|k]ustomize the way they want, downstream.

**Comment by izelnakri** [comment]
@vsliouniaev havent seen them yet but based on my use them seem needed. @haf I think Helm should make versioning declarative with `package.json`(maybe helm.json) and `helm_charts` folder. Of course put all the manifests under one file however versioning it and updating it is still a challenge. In my opinion, helm will eventually need to have explicit versioning and most CNCF projects are getting deployed and used as helm charts across the board, thus it is better to support helm directly.

**Comment by lilic** [comment]
> how about having plain kubernetes manifests in this repo? 

We have plain manifests in this repo -> https://github.com/coreos/prometheus-operator/tree/master/example :)

**Comment by haf** [comment]
> We have plain manifests in this repo 

Yes, but I mean a complete setup that I can point my kustomization to. Would you let me PR what I mean?

**Comment by lilic** [comment]
This seems like a problem with kustomize if it needs very specific directory or something for it. We have this https://github.com/coreos/prometheus-operator/blob/master/kustomization.yaml no idea around the backstory for it nor do I use kustomize, but yes if it doesn't work lets fix it, as it seems like it worked before?

cc @brancz whats the history around that file?

**Comment by paulfantom** [comment]
Full working kustomize setup is provided by kube-prometehus repository. Kustomize file is available at https://github.com/coreos/kube-prometheus/blob/master/kustomization.yaml

**Comment by haf** [comment]
Ok, let's review improvement opportunities for those:

- [grafana dashboards definitions](https://raw.githubusercontent.com/coreos/kube-prometheus/master/manifests/grafana-dashboardDefinitions.yaml) — too large, you'll run into problems applying; instead use configMapGenerator in kustomization.yaml and point to plain json files. The upside of this is a clean workflow from Grafana where you create the dashboard, to JSON files, which kustomize will pick up
- [grafana deployment](https://github.com/coreos/kube-prometheus/blob/master/manifests/grafana-deployment.yaml) — this should be split into a separate folder, so we don't have to deploy and old grafana just to use prometheus operator; create a folder per 'concept' and let me as the user compose the setups I care about
- [extra configmaps](https://github.com/coreos/kube-prometheus/blob/master/manifests/prometheus-adapter-configMap.yaml) should be created using kustomization.yaml and the above configMapGenerator, so that we don't have to keep nesting yaml with JSON, but can edit the JSON in a JSON editor
- `setup` as a folder is not really expressive
- Where's the admission hook?
  - and its role binding etc
- Where's the validating hook?
  - and its role bindings etc
- Alertmanager is missing a pod security policy
- kust-state-metrics is missing a pod security policy
- node-exporter is missing a pod security policy

Need to update https://github.com/coreos/prometheus-operator#prometheus-operator-vs-kube-prometheus-vs-community-helm-chart with the info that the above is the recommended way

**Comment by paulfantom** [comment]
> Ok, let's review improvement opportunities for those:

This is something should be discussed in another issue in kube-prometheus.

**Comment by haf** [comment]
> Need to update https://github.com/coreos/prometheus-operator#prometheus-operator-vs-kube-prometheus-vs-community-helm-chart with the info that the above is the recommended way

**Comment by paulfantom** [comment]
> the info that the above is the recommended way

There is no one recommended way and don't plan on recommending one other the other in prometheus-operator repository. Readme points out the differences between two different mechanisms of deploying stack and it is out for the end-user to decide which one is the one he or she wants to use.

We as maintainers of prometheus-operator use jsonnet from kube-prometheus to generate deployment manifests. We don't directly use kustomize nor we use helm. However since kustomize only needs one file to list all plain yaml manifests, we added that to kube-prometheus project and we are open to ideas and contributions to kube-prometheus project :)

**Comment by brancz** [comment]
FWIW I think the list of suggestions are awesome! Let’s work on those things! :)

**Comment by haf-afa** [comment]
Ok, here's the WIP https://github.com/coreos/kube-prometheus/pull/523

**Comment by sc250024** [comment]
I think the thing to do here is to use Bitnami's Prometheus Operator Helm chart here: https://hub.helm.sh/charts/bitnami/prometheus-operator. They seem to have integrated most of the core functionality into the chart, and they maintain their charts very well.

On a longer note, I'm really not sure why the maintainers / people in general have such a revulsion to Helm. Having used it extensively myself, I know it's strengths and weaknesses quite well. It's a legitimate packaging format for Kubernetes and is now CNCF Graduated. Does it do everything? No, but no tool does.

**Comment by brancz** [comment]
We've had our share of experience with it as well and we chose to abandon it because of that. We replaced it with something we're happier with :) We've run this project for >4 years now, helm chart maintainers come and go every ~6 months. We're promised maintainership and then people abandon it because it's too hard to maintain. We've experienced this too often to have this happen in the main repo again. If this happens in a separate repo, then it's easier for us to distance ourselves from it and not have the responsibility fall back on us (like it has happened repeatedly before).

**Comment by sc250024** [comment]
@brancz That's a good point. Is the issue you all have with Helm itself (i.e. its method of constructing the manifest), or with the fact that there's no steady maintainer? What tool do you all use instead?

**Comment by lilic** [comment]
> What tool do you all use instead?

We (in openshift) use operators (controllers) to reconcile and further customize manifests that are generated by prometheus https://github.com/coreos/kube-prometheus.

**Comment by scottrigby** [comment]
Hello everyone! I was here from Freenode #prometheus-dev IRC channel, where I'm discussing moving the `stable/prometheus-operator` helm chart to a new home in advance of the `stable` and `incubator` helm repo deprecation this November (see https://github.com/helm/charts/issues/21103 for tracking that progress overall).

Related to this issue discussion, I want to mention that as of Helm `3.1.0` there is a [post-renderer flag](https://helm.sh/docs/topics/advanced/#post-rendering) that allows end users to customize chart output for their specific use cases. This can allow charts to be dramatically simplified. You can see a demo for how to use kustomize as the post-renderer here: https://github.com/thomastaylor312/advanced-helm-demos/tree/master/post-render

We will be presenting on this during the Helm Deep Dive KubeCon EU 2020 session coming up, but you don't need to wait for that to check it out. I'm mentioning here to address concerns posted above.

As part of the goal of moving stable charts to new homes, my main question is: should `stable/prometheus-operator` be moved to the https://github.com/prometheus-operator or the https://github.com/prometheus-community GitHub org?

**Comment by scottrigby** [comment]
I should also note we have created Helm GitHub actions to make this an easy process, and myself and several others are volunteering to set up the new homes for these charts with essentially the same CI/CD as github.com/helm/charts use today. I also suggest using a separate git repo for the charts, and bringing in previous history from stable the stable chart(s) (git filter-branch etc) to not only make the automation process smooth, but also the process of future maintenance. Please hit me up for help with that once the best org for this chart is decided. I can give recommendations for processes, and help with setup, but I where the prometheus-operator chart should live is is better discussed between members of the two orgs.

**Comment by lilic** [comment]
I am curious @scottrigby you mentioned you would help setup, but who would maintain these charts? My fear of adding them to our org is that we the maintainers of the org would eventually be responsible for them which has happened in the past. Wonder why did they not move just within the helm organization, and why is there a need to move it to each org instead of under `helm` for example?

I am not blocking the move, just trying to understand what this means for us maintainers, as we ourselves (the majority of us) don't use the helm chart so would be harder to maintain it in the long run. If people decide to not maintain it, do we remove the helm chart what is the process there? Thanks!

**Comment by brancz** [comment]
I kind of agree with @lilic's direction. Projects don't tend to maintain all flavors of deb, rpm, flatpak, snap, ebuilds, pacman, etc. either. I guess the biggest problem I have with putting it in the prometheus-operator org is a kind of "endorsement" that that would give towards that solution, which does not exist in the current set of maintainers. I'm all for enabling the community to have helm charts, so because of that and the above reasoning I think the prometheus-community org is a good place for the helm chart. I'm happy to sponsor the helm charts going into the prometheus-community org, under the condition that it's renamed to `kube-prometheus-chart` to more accurately reflect its content.

Aside from that, I'm excited to see how what you mentioned @scottrigby works out in practice around minimal helm charts, and hope to see the chart evolve in that direction.

**Comment by scottrigby** [comment]
@lilic to start it sounds like it would be two of the [current maintainers](https://github.com/helm/charts/blob/master/stable/prometheus-operator/OWNERS) (I just reached out to the third again to check in, they had stepped back for a time but wanted to remain present to help merge PRs as needed), and also at least one more person [volunteered](https://github.com/prometheus-community/community/issues/28#issuecomment-670012626) in the related thread. However I don't have an opinion on where it should move, only to help once a new home is decided 😄 

Quick answer to your question about why not move the chart to the Helm org: while monorepos for related charts is an idiomatic approach, having _all_ the charts in one repo proved to be unsustainable. Several years ago when the [Distributed Repositories](https://github.com/helm/community/blob/master/proposals/distributed-search.md) proposal was made I initially suggested breaking the charts up into individual git repos under the helm org, and then if/when more appropriate homes were found they could be transferred, but this would pose a problem for communities that want to move related charts back to one monorepo in their own org (more difficult at that point to splice the git history back together), so we instead used this year to work with app communities to identify their forever homes before moving over the appropriate chart(s) with history from helm/charts the the new location. Hope this makes sense?

**Comment by scottrigby** [comment]
@brancz OK that makes sense, especially with what @lilic is saying 👌 

Since you are [sponsoring](https://github.com/prometheus-community/community/issues/28#issuecomment-669932123) the prometheus-operator chart for prometheus-community, and prometheus-operator devs feel the prometheus-operator org is not the ideal home for the chart, it sounds like we can follow up in https://github.com/prometheus-community/community/issues/28 and close this issue 👍 Thanks everyone!

**Comment by lilic** [comment]
Thanks for your explanation! Happy to hear of that outcome, just want it to find a permanent home.

**Comment by scottrigby** [comment]
This is now complete ✅  I thought I had updated it everywhere, but just remembered this issue.

https://twitter.com/r6by/status/1303742371427909632?s=20
> 📢 Big news for prometheus users and contributors: the 
@HelmPack stable Prometheus charts (17 of them) have moved to https://github.com/prometheus-community/helm-charts 🎉 🥳
>
> Find them on CNCF Artifact Hub: https://artifacthub.io/packages/search?page=1&org=prometheus&kind=0 🕵️‍♀️ 🔎
>
> Contribute here: https://github.com/prometheus-community/helm-charts 🙋‍♂️

https://twitter.com/r6by/status/1303744992717008900?s=20
> 🚧 Important change notice: the stable "prometheus-operator" chart name has changed:  it's now "kube-prometheus-stack", to more accurately reflect the upstream project it installs: https://github.com/prometheus-operator/kube-prometheus. Enjoy!

(also see the thanks tweet in that thread. mainly wanted to post news here)

**Comment by paulfantom** [comment]
Closing issue as helm chart is now maintained at https://github.com/prometheus-community/helm-charts
