### ISSUE TITLE
Vulnerability scanner for prometheus-operator

### ISSUE THREAD

**Issue by rayotte** [prometheus-operator/prometheus-operator#3188]
* Prometheus Operator version:

   prometheus-operator 0.38.1 (8.13.0 helm chart)

* Kubernetes version information:

   client: 1.17.0
   server: 1.15.5

Is there a way to do CVE vulnerability scan for prometheus-operator (and other busybox) image? Tried both Clair and Anchore scanners but both did not work for images with busybox bases

**Comment by brancz** [comment]
I am not aware of a scanner that scans busybox.

That said prometheus operator is a statically linked binary, so scanning the image isn't going to help you a whole lot, as what you run isn't concerned with it. At the very most maybe the root CAs are interesting but are updated whenever a new debian package is released, which doesn't happen very often (debian because that's where the prometheus busybox base image gets the certs from).

**Comment by paulfantom** [comment]
Closing as the issue appears to be answered. If you need additional clarification, please reopen it.
