### ISSUE TITLE
Override readiness/liveness values for prometheus

### ISSUE THREAD

**Issue by wandersonfdias** [prometheus-operator/prometheus-operator#3216]
What did you do?
Change Readiness/Liveness config for prometheus

What did you expect to see?
Define values override readiness/liveness into values.yaml file.

What did you see instead? Under which circumstances?
No values are available and prometheus use default values for both config.

Related chart: https://github.com/helm/charts/tree/master/stable/prometheus-operator

**Comment by brancz** [comment]
Can you explain why? :)

**Comment by wandersonfdias** [comment]
Hi, Frederic. How are you?

So, currently I'm using a stable version of prometheus-operator chart
(8.13.x).

Analysing the prometheus POD probes, we have these configurations:

    livenessProbe:
>       failureThreshold: 6
>       httpGet:
>         path: /-/healthy
>         port: web
>         scheme: HTTP
>       periodSeconds: 5
>       successThreshold: 1
>       timeoutSeconds: 3
>     readinessProbe:
>       failureThreshold: 120
>       httpGet:
>         path: /-/ready
>         port: web
>         scheme: HTTP
>       periodSeconds: 5
>       successThreshold: 1
>       timeoutSeconds: 3


Readiness Probe will fail after 10 minutes (120 attempts distributed at 5
seconds periods).
Liveness Probe will fail after 30 seconds (6 attempts distributed at 5
seconds periods).

Currently, I have a small/medium Kubernetes cluster with 20 worker nodes, 3
master nodes  and 3 etcd nodes.

I realized that in our cluster, if it was possible do change livenessProbe
default configurations, we will have a better use.
In some scenarios, when the volume of data to scrape are high, until we
adjust the memory/cpu resources, the prometheus POD has a lot of restarts
(because livenessProbe failing).

Regards,

Wanderson Ferreira Dias
Solution Architect
Cloud and Microservices Architecture

Linkedin: https://www.linkedin.com/in/wanderson-dias-0b784327/

**Comment by jagguli** [comment]
I have a situation where prometheus is running a repair job on start, hence it does not report as ready, until the repair completes

But because readiness fails the container keeps getting restarted.

**Comment by wandersonfdias** [comment]
Hi @brancz . How are you?

Could you review my previous request?

Regargs,

Wanderson.

**Comment by paulfantom** [comment]
> I have a situation where prometheus is running a repair job on start, hence it does not report as ready, until the repair completes

This should be fixed by including startupProbe, more in https://github.com/coreos/prometheus-operator/issues/3211

> I realized that in our cluster, if it was possible do change livenessProbe
default configurations, we will have a better use.
In some scenarios, when the volume of data to scrape are high, until we
adjust the memory/cpu resources, the prometheus POD has a lot of restarts
(because livenessProbe failing).

Setting different readinessProbe/livenessProbe parameters, in this case, won't help you as your prometheus server is overloaded and simply needs more resources to operate. Adjusting memory limits and requirements is the right thing to do in such scenario.

**Comment by wandersonfdias** [comment]
Thanks, @paulfantom.

This will solve my problem.

**Comment by desaintmartin** [comment]
We have a similar case where a Prometheus managed by Prometheus Operator is temporarily overloaded because of huge requests. Allowing to customize livenessProbe/readinessProbe parameters would allow us to loosen a bit the probes in order to give more time to Prometheus to finish to process (or abort) those requests before killing it.

Prometheus, in this case, does not need MORE resources because this is very temporary (in our case, a developer playing with not-optimized requests), but in this case killing it so soon is worse than not killing it at all and wait more.

**Comment by paulfantom** [comment]
We removed livenessProbe in Prometheus in https://github.com/prometheus-operator/prometheus-operator/pull/3502 and will reintroduce them when startupProbe is mature enough. This should close the issue for now.

**Comment by wandersonfdias** [comment]
Thanks, @paulfantom.
