### ISSUE TITLE
Remove the need for custom multi namespace listwatcher

### ISSUE THREAD

**Issue by lilic** [prometheus-operator/prometheus-operator#3339]
This has caused a few problems in the past, and made it difficult to debug due to its nature. 

TODO: write up plan on how to remove this, possibly using https://v1-17.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#labelselectorrequirement-v1-meta

See background https://github.com/coreos/prometheus-operator/issues/3218

**Comment by s-urbaniak** [comment]
A couple of investigational findings which we partially discussed OOB and partially found from my side as a continuation of the investigation:

- As far as I understand we cannot use `LabelSelectors` (or the type safe `LabelSelectorRequirement` variant) in conjunction with limiting the query results with a global listwatch, because a) namespaces cannot be specified using label selectors and b) a global listwatch would brake invariants expressed here https://github.com/prometheus-operator/prometheus-operator/pull/3409#issuecomment-673336358.

Continued investigation revealed that selectors are still useful though! The `FieldSelector` can indeed be used to limit namespaces as per https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/. While not useful for the allowlisting use case it is very much useful for the denylisting use case as described in https://github.com/prometheus-operator/prometheus-operator/issues/3410#issuecomment-677268380.

- Another security related argument expressed here https://github.com/prometheus-operator/prometheus-operator/pull/3409#issuecomment-673337444 indicates why individual list watchers have to be used.

Instead, the proposal is to continue using an array of list watchers, this time not wrapped with a custom `ListWatcher` interface, but rather using an array of `Informers` instead. Previous work in https://github.com/openshift/library-go/blob/ab277dcc0384e180c6bb5e1f2cd2120143b2093c/pkg/operator/v1helpers/informers.go#L16-L23 shows that this approach is already being used elsewhere.
