### ISSUE TITLE
Deploying without thanos and podmonitors

### ISSUE THREAD

**Issue by rrpai** [prometheus-operator/prometheus-operator#3371]
Hi All

- Our kubernetes cluster does not have Thanos or podmonitors
- The operator 0.40.0 version looks for thanos and podmonitors and fails
- Is there a way to disable it looking for them

logs
```
E0728 11:20:53.746066       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:311: Failed to list *v1.ThanosRuler: the server could not find the requested resource (get thanosrulers.monitoring.coreos.com)
E0728 11:20:53.754813       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:479: Failed to list *v1.PodMonitor: the server could not find the requested resource (get podmonitors.monitoring.coreos.com) 
```
- I tried this in values.yaml in helm chart, but no effect

```
prometheus:
  prometheusSpec:
    thanos:
      create: false
```

**Comment by brancz** [comment]
This is just about the CRDs, you don't need to make use of them. There is no way to disable watching for them.

**Comment by sebastienbonami** [comment]
Hi, is it possible now to disable the watch of certain CRDs? Thanks.

**Comment by simonpasquier** [comment]
@sebastienbonami what's exactly your use case?

**Comment by sebastienbonami** [comment]
@simonpasquier I'm doing Prometheus Federation and my federated Prometheuses don't need most of components like Alertmanager, Thanos, etc.

I'm using this Helm Chart: https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack/54.1.0

Even if I set `enabled` to `false` for `alertmanager` and `thanosRuler`, the operator is still watching for their CRDs.

The less CRDs to install the better as each time they are applied it's an overhead, so that's why I would like to avoid installing all of them 10 (https://github.com/prometheus-operator/prometheus-operator/tree/v0.69.1/example/prometheus-operator-crd).

Thanks for your help.

**Comment by simonpasquier** [comment]
Ack, the operator already supports that some CRDs aren't installed (e.g. PrometheusAgent, ScrapeConfig). Would you mind create a new issue?

**Comment by sebastienbonami** [comment]
New issue: https://github.com/prometheus-operator/prometheus-operator/issues/6140
