### ISSUE TITLE
What is canonically correct way to `go mod download` `.../pkg/apis/monitoring/v1`

### ISSUE THREAD

**Issue by notjames** [prometheus-operator/prometheus-operator#3442]
What is the proper way to using go mod to obtain `"github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1"`  that will not update all of my vendor libs? I just need to import the `v1` api there to set and read `servicemonitor`s in my clusters programmatically.

```
$ go mod download -x github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1
module github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1: not a known dependency
```
or
```
$ go get github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1
go: found github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1 in github.com/coreos/prometheus-operator v0.41.1
```

my imports
```
import (
	"context"
	"encoding/base64"
	"fmt"
	v1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/util/intstr"
	"strings"
	"text/template"
	"time"

	"github.com/google/uuid"

	coreosv1 "github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1"
	"github.com/go-kit/kit/log"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/tools/clientcmd"
)
```

The actual code I'm using this library for looks like:
```
	// define service monitor object
	serviceMonitorObject := &coreosv1.ServiceMonitor{
		ObjectMeta: metav1.ObjectMeta{
			Name:      objectMetaDataName,
			// TODO: fix namespace
			Namespace: "monitoring",
			Labels:    labels,
		},
		Spec: coreosv1.ServiceMonitorSpec{
			Selector: metav1.LabelSelector{
				MatchLabels: labels,
			},
			NamespaceSelector: coreosv1.NamespaceSelector{
				MatchNames: []string{
					"monitoring",
				},
			},
			Endpoints: []coreosv1.Endpoint{
				{
					Port: "metrics",
					Interval: "10s",
					HonorLabels: true,
				},
			},
		},
	}
```

However, I cannot seem to just import the one library. Any suggestions or assistance would be greatly appreciated.

**Comment by notjames** [comment]
Unfortunately, I had to bite the bullet and run `go mod tidy` which jerked versions around for the entire vendor library affecting ~950 files.

**Comment by grdryn** [comment]
(I'm not a maintainer of prometheus-operator, but I hope some of the below might help)

What version of Go are you using (this might be relevant if people look back on this issue in future and get confused because tools have changed or something)?

I think using the `replace` directive in the `go.mod` file might help a little. See more info on that [here](https://golang.org/ref/mod). That might be a slippery slope though, as you'd be changing the versions of dependencies that things expect, maybe to something invalid. I'd tend to only reach for that if `go mod tidy` failed.

What are the problems you see with those vendored files being changed? If `go mod tidy && go mod vendor` ran successfully, then the module system has found versions that work with your existing dependencies and the prometheus-operator version that you've added (maybe the prometheus-operator demands a higher or lower version of some dependency that you use directly, or is pulled in by one of your other dependencies).

Another aspect of this (if it's mostly the repo churn that you're concerned with) is: is vendoring dependencies still important to you, now that you use Go modules? I believe there are a growing number of projects that previously vendored dependencies, but no longer see the value in it because of the guarantees that the modules system now provides (including this project, see #3386). Of course, you may still have requirements to vendor, but it's something to think about if you don't and it alleviates the issue that you have. :slightly_smiling_face:

**Comment by notjames** [comment]
I'm using go version `go1.14.6`. 

So the problem with the vendored files changing seemed to be mostly related to kubernetes libs. I can't speak to the specifics of what or why but after I ran `go mod tidy`, I ended up having to fix ~20 functions where `ctx` wasn't getting passed in as the first argument, so something seemed to force that requirement whereas before the run of `go mod tidy` those functions worked fine. That was really the biggest problem as far as I can tell so far. At the least it was a PITA to fix taking some time out of my day and switching context to fix. 

I need to look into modules vs vendored deps. I was under the impression that we were using modules (don't modules still reside in the `vendor` directory?) -- being so new to go, I am not yet able to answer that question very well right now.

**Comment by notjames** [comment]
> (I'm not a maintainer of prometheus-operator, but I hope some of the below might help)
> 
> What version of Go are you using (this might be relevant if people look back on this issue in future and get confused because tools have changed or something)?
> 

I'm using go version `go1.14.6`. 

> I think using the `replace` directive in the `go.mod` file might help a little. See more info on that [here](https://golang.org/ref/mod). That might be a slippery slope though, as you'd be changing the versions of dependencies that things expect, maybe to something invalid. I'd tend to only reach for that if `go mod tidy` failed.
> 
> What are the problems you see with those vendored files being changed? If `go mod tidy && go mod vendor` ran successfully, then the module system has found versions that work with your existing dependencies and the prometheus-operator version that you've added (maybe the prometheus-operator demands a higher or lower version of some dependency that you use directly, or is pulled in by one of your other dependencies).
> 

So the problem with the vendored files changing seemed to be mostly related to kubernetes libs. I can't speak to the specifics of what or why but after I ran `go mod tidy`, I ended up having to fix ~20 function call arguments where `ctx` wasn't getting passed in as the first argument, so something seemed to force that requirement whereas before the run of `go mod tidy` those functions (where ctx was not explicitly passed) worked fine. I also had to fix some function callers to explicitly pass ctx. That was really the biggest problem as far as I can tell so far. At the least it was a PITA to fix taking some time out of my day and switching context to fix. 

> Another aspect of this (if it's mostly the repo churn that you're concerned with) is: is vendoring dependencies still important to you, now that you use Go modules? I believe there are a growing number of projects that previously vendored dependencies, but no longer see the value in it because of the guarantees that the modules system now provides (including this project, see #3386). Of course, you may still have requirements to vendor, but it's something to think about if you don't and it alleviates the issue that you have. 🙂

I need to look into modules vs vendored deps. I was under the impression that we were using modules (don't modules still reside in the `vendor` directory? How can one tell one is using one over the other?) -- being so new to go, I am not yet able to answer that question very well right now.
