### ISSUE TITLE
Automatically deploy blackbox_exporter when a probe is defined

### ISSUE THREAD

**Issue by RiRa12621** [prometheus-operator/prometheus-operator#3514]
**What is missing?**
A blackbox_exporter deployment

**Why do we need it?**
With the recent addition of synthetic probes, it is possible to easily create blackbox exporter probes, however this still requires a blackbox exporter deployment to exist on cluster in order to work.

A more convenient over a user manually deploying it, would be for prometheus operator to create said deployment, once the first probe CR is defined and picked up.

**Comment by paulfantom** [comment]
I don't think prometheus-operator should deploy blackbox_exporter. The same way it is not deploying node_exporter or kube-state-metrics.

In the current iteration Probe CRD gives users full flexibility over where checks are coming from and according to best practices blackbox monitoring should be done from the outside of the cluster to mimic user requests. The majority of cases inside the cluster should be done by whitebox monitoring, where metrics are exposed by the application itself. With such an approach prometheus-operator cannot manage blackbox_exporter simply because it is not in the same cluster.

**Comment by RiRa12621** [comment]
I think the key difference here is that neither node_exporter nor KSM are explicitly required by prometheus-operator components in order to fully work.
Essentially a Probe will not work without a blackbox_exporter, if i understood correctly. If I did in fact misunderstand that part, then we can cut it short at this point.

Thinking of isolated clusters or users with only a single cluster: they basically don't have any option except to have whitebox and blackbox monitoring on the same cluster. Additionally some users may just want to have their setup self contained for each cluster. Speaking a little less hypothetical that's the setup OpenShift Dedicated would prefer for a variety of reasons starting with compliance.

So while blackbox probes should come from the outside, there are some not so rare cases where they will be coming from the inside.

**Comment by paulfantom** [comment]
> Essentially a Probe will not work without a blackbox_exporter

Neither ServiceMonitor without a Service, not PodMonitor without a Pod. This doesn't mean prometheus-operator should provision those.

> So while blackbox probes should come from the outside, there are some not so rare cases where they will be coming from the inside.

I agree that there as such cases, but if we start provisioning blackbox_exporter pods, we are setting a pattern of usage for it. And in this case, this would be an anti-pattern for a lot of environments. I think it would be good to include blackbox_exporter as a jsonnet patch (one ConfigMap, one Deployment, and one Service) to kube-prometheus project. This way we can provide an unopinionated way of managing this component.

**Comment by RiRa12621** [comment]
>Neither ServiceMonitor without a Service, not PodMonitor without a Pod. This doesn't mean prometheus-operator should provision those.
You got me there

kube-prometheus sounds like a good way forward to me.
Closing.
If anyone has strong feelings about this, I think they can still comment and/or re-open the issue

**Comment by brancz** [comment]
Another perspective (same result): At one point I actually thought about defaulting blackbox exporter configuration, but even that I think goes too far. It's not uncommon that you have multiple blackbox exporters so you ping probe from multiple geolocations.

**Comment by kehao95** [comment]
Hi there, I read your discussions and I agreed on your points, until I really tried to use it.

I was trying to probe some http endpoints inside/outside my k8s cluster. Then the first challenge I meet was to deploy an `node_exporter` fits into the `ProberSpec` which takes an `url` not an `selector`. **URL** makes sense since we may leverage the prober outside the cluster. But it makes it hard to locate an `node_exporter` deployment compare to selector. I may have to create a Deployment & Service & setup an internal DNS record for it. 
Then I start to ask myself, why should it be so complicated.

### Users are expecting the similar experience 
I reviewed the quote then I realize it's a bad one. 
> Neither ServiceMonitor without a Service, not PodMonitor without a Pod.  

In those cases users have Pod/Service already. Then user just need to tell PrometheusOperator to scrape on them. And natually user may expect same experience the same experience when it comes to blackbox probe
**I have targets already, I just need to tell PrometheusOperator to probe on them.**
And that's not working like that yet.


### Probe "is" a prometheus feature
This will make sense if we consider **probe** as a prometheus feature just like `scrape/rule-evaluation/alerting...` even though it's achieved by an outer component `blackbox_exporter`.  
To be honest, doesn't the same applies to **Alerting**, needing the help of `alertmanager`. But we still integrate alertmanager as part of PrometheusOperator. We help Alerting works out-of-box regarding the fact that Prometheus can use outer Alertmanagers.  
And **Thanos**, that's even not a prometheus feature.


### Current approach is not ideal.
As I mentioned before. URL spec is not ideal for k8s deployment we add extra resources for users to manage. And the current API seem to be wrong -- if we don't manage a default prober why the prober filed is *optional*

### Suggestion: deploy node_exporter aside Prometheus (when needed)
Let's keep the current Doc as is where you can specific `prober` but it's optional.
When `prober` is specified prometheus use that external prober.
When there are `Probe` without `prober` specified. We deploy the `node_exporter` within the prometheus pod ( so it's tight to prometheus as if an extension) And prometheus use that to probe.

**Comment by kehao95** [comment]
@brancz @paulfantom @RiRa12621 
Maybe this is closed so you didn't see my comments. Just want to bring your attention on this again.

**Comment by paulfantom** [comment]
Probe is designed for external blackbox checks (hence why `blackbox_exporter` is necessary). In the current form it has a potential that other exporters might be used, for example maybe sth like [smokeping_prober](https://github.com/SuperQ/smokeping_prober) could be adapted for this purpose. This means a `Probe` has potential to be used with other exporters, which are designed in similar way as `blackbox_exporter`. That said I don't see how node_exporter fits into this. `node_exporter` should be scraped using `ServiceMonitor` or `PodMonitor`, not `Probe`.

Additionally, if we add `blackbox_exporter` to be deployed by prometheus-operator, there are zero guarantees any data will be gathered as external probe targets need to be first defined by the user. Which means we would be deploying a dead resource. This is also why any prober deployment (ex. blackbox_exporter) should be optionally deployed with kube-prometheus.
