### ISSUE TITLE
Editing prometheus operator file

### ISSUE THREAD

**Issue by edvinas31** [prometheus-operator/prometheus-operator#3556]
Hello, I am using OKD (however 3.11) version and I was unable to find any way to edit prometheus rules file permanently. I know that it is possible to change Alertmanager file using ansible variable openshift_cluster_monitoring_operator_alertmanager_config (https://docs.openshift.com/container-platform/3.11/install_config/prometheus_cluster_monitoring.html). It would be great to be able customise alert rules and to change prometheus configuration using ansible variable. Is there any way to do that keeping mind that prometheus-operator overwrites manually edited configuration?

**Comment by lilic** [comment]
Hey @edvinas31 this is an upstream repo that is only one part of OpenShift monitoring stack, but can answer as I work on monitoring in OpenShift, best next time best open these questions in OpenShift or ask on other slack channels. 

cluster-monitoring-operator in openshift is the one that modifies these files and application monitoring and custom alerting rules is in OpenShift starting with 4.3 onwards which is what I think you are looking for, best to switch to that version. Hope that answers your question, otherwise best ask red hat support or other OKD channels. Thanks! :)
