### ISSUE TITLE
Clarify number of approval needed for merging a pull request

### ISSUE THREAD

**Issue by lilic** [prometheus-operator/prometheus-operator#3563]
We seem to be not consistent currently in our way of merging a PR. Sometimes we require 1 person, sometimes 2, etc. While there is nothing wrong with getting a second opinion, we should still document the lowest number of approvers needed to merge the PR. @paulfantom suggested we can easily enforce this via our tooling settings on github. 

@prometheus-operator/prometheus-operator-reviewers Would you prefer to require 1 approval 👍 or 2 approval at least to merge any PR? Other suggestions welcome!! :)

When the majority agrees we can also document this in the [CONTRIBUTING](https://github.com/prometheus-operator/prometheus-operator/blob/master/CONTRIBUTING.md) file.

**Comment by simonpasquier** [comment]
My (personal) decision tree is:
* if it's a simple PR (typo, logging enhancement, bug fix with a test), I'm fine with a single approval.
* for anything that I feel is more involved, I ask for multiple reviews.

If we want to enforce anything in GitHub, I'd vote for requesting 1 approval before merging. Otherwise I suspect that it will slow down the contributions more than anything.

**Comment by brancz** [comment]
I tend to agree it depends on the situation. I think 1 approval is necessary, and I only ask for more if I feel the change is risky enough. In Thanos, the rule is that if anyone (reviewer or creator of PR) thinks that a second review is required, then we explicitly write that on the PR and ping specific people we would like to see a review from. I think this works pretty well.

**Comment by simonpasquier** [comment]
For the record, the GitHub UI requires 1 explicit approval before merging.
