### ISSUE TITLE
Snapshot generation for second replica

### ISSUE THREAD

**Issue by mohanagandlla** [prometheus-operator/prometheus-operator#3649]
Hi I am maintaining the 2 replicas for Prometheus and 2 replicas are having the different PV the Prometheus is in version at 2.22.0 
I am going to generate the snapshot for data back up it is working only on 1 replica I mean the snapshot is generating only on the first replica how to collect the snapshot on the second replica?

**Comment by brancz** [comment]
You will need to specifically do requests against each replica to do this.

**Comment by mohanagandlla** [comment]
May I know how to give request specifically

**Comment by brancz** [comment]
Because Prometheus is deployed in a statefulset, it should be something along the lines of

* `prometheus-<prometheus-object-name>-<replica-ordinal>.prometheus-operated.<namespace>.svc`

So for a `Prometheus` called `k8s` in the `monitoring` namespace with 2 replicas, that would be:

* `prometheus-k8s-0.prometheus-operated.monitoring.svc`
* `prometheus-k8s-1.prometheus-operated.monitoring.svc`

**Comment by mohanagandlla** [comment]
Ya thank you
