### ISSUE TITLE
Latest prometheus-operator image unavailable in registry

### ISSUE THREAD

**Issue by diyavicky** [prometheus-operator/prometheus-operator#3672]
Team,

when we are trying to pull latest prometheus-operator image its unavailable in docker registry.
https://quay.io/repository/coreos/prometheus-operator?tab=tags

Latest image that we could see is **v0.42.1**

Could you please advise on this.

Thanks!

**Comment by paulfantom** [comment]
As stated in [0.41.0 release notes](https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.41.0) we dropped coreos repository after migration to the new organization. Since 0.43.0 images are only pushed to [prometheus-operator organization](https://quay.io/organization/prometheus-operator) on quay.io.

**Comment by diyavicky** [comment]
Thanks for the update!
