### ISSUE TITLE
How to modify prometheus Retention at run time ?. 

### ISSUE THREAD

**Issue by SAbdulRahuman** [prometheus-operator/prometheus-operator#3731]
**What did you do?**
  I'm using openshift cluster and prometheus operator is installed and Prometheus,AlertManager are running. Now i have a request to change prometheus **Retention** (i.e, 100d), Mainly i'm looking REST API to change it , Is there any REST API available to change prometheus Retention at runtime?

**Environment**
  Openshift cluster 4.6

**Comment by simonpasquier** [comment]
The retention is controlled by CLI flags only. Check the `spec.retention` and `spec.retentionSize` fields in the Prometheus CRD.

**Comment by lilic** [comment]
Since you are using openshift, check the openshift [docs here](https://docs.openshift.com/container-platform/4.6/monitoring/configuring-the-monitoring-stack.html#modifying-retention-time-for-prometheus-metrics-data_configuring-the-monitoring-stack) we have this documented as you cannot modify the Prometheus resource directly but via a ConfigMap. But for where you have control over the Prometheus resource, its what Simon said above.

**Comment by SAbdulRahuman** [comment]
Thanks **simonpasquier** and **lilic** for answers and the link. Now i got the idea and able to modify prometheus "Retention".

My requirement was to modify `retention` at runtime based on user's request.

**Comment by simonpasquier** [comment]
@SAbdulRahuman I'm closing it since modifying retention at runtime isn't supported by Prometheus.
