### ISSUE TITLE
CRD Update lifecyclle

### ISSUE THREAD

**Issue by yeplaa** [prometheus-operator/prometheus-operator#3873]
**What did you do?**

I test the version upgrade of Prometheus for my cluster from 0.43 to 0.45. On the update of CRD Alertmanagerconfigs, the behavior of a CRD manifest is updated without changing the version field on a CRD. I wondered what the impact was for the CR deployed with 0.43 version. What is your version upgrade strategy to avoid impacts on CRs already deployed?

**Did you expect to see some different?**

If need, update of content CRD manifest with the native field Served, Storage update.

**Environment**

* Prometheus Operator version:

I use the Helm Packaging of kube-prometheus-stack repo.
Update from 12.3.0 to 13.13.0 Helm Package.

**Comment by coderanger** [comment]
Resource versions are only updated when there's either a major schema change that isn't backwards compatible or when indicating a new version has reached an expected stability threshold (that's schema stability, not operational stability). It doesn't change much since almost all changes are adding new fields which can be backwards compatible :)

**Comment by brancz** [comment]
The `AlertmanagerConfig` CRD specifically is v1alpha1, so there are no stability guarantees around this yet whatsoever. The point is to allow us some time to ripen the schema and functionality before we have to support it essentially for life :)

**Comment by yeplaa** [comment]
Thanks @coderanger , @brancz for your quick reply. :)
Regarding prometheuses.monitoring.coreos.com CRD that is v1,  are you on the strategy indicated by @coderanger , that's right?

**Comment by brancz** [comment]
Correct.
