### ISSUE TITLE
Add an owner reference to Prometheus resources pointing to the PO instance that reconciled them

### ISSUE THREAD

**Issue by fpetkovski** [prometheus-operator/prometheus-operator#4281]
**What is missing?**
The Prometheus Operator should add an owner reference on all Prometheus, Alertmanager and ThanosRuler resources that it manages. During the reconciliation loop, the Prometheus Operator should skip instances of these resources that are already owned by another Prometheus Operator instance.

**Why do we need it?**
When multiple PO instances run in the same cluster with overlapping selectors, they can interfere with each other by reconciling the same resources. 

**Environment:** Any

**Prometheus Operator version:** Any

**Anything else we need to know?**:
The mechanism of single ownership has already been described and implemented for several Kubernetes resources: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/controller-ref.md#controllerref-proposal

**Comment by slashpai** [comment]
I will take a look at this :)

**Comment by simonpasquier** [comment]
@paulfantom yes the cross-namespace issue is real but maybe we can at least make it work for the case where the Prometheus operator pod and managed resources live in the same namespace?
Another hurdle is how we make sure that deleting a Prometheus operator's pod doesn't remove the resources it used to manage?

**Comment by Haleygo** [comment]
> So it leaves only the .Status part as todo.

Hi, is there any process on populate CR .Status?

> In such scenario, when operator detects that it wants to manage a CR, but it conflicts with another operator due to field being populated, it should emit an event + increase a value for a metric. Based on that metric we can create an alert and actively notify end user about this issue.

This metric sounds interesting too.

**Comment by simonpasquier** [comment]
Resurrecting this issue because this is a real problem in environments like OpenShift where 1 monitoring stack is responsible for platform monitoring and users may deploy their own Prometheus operator instances in parallel. The remediation is to use one of the many CLI arguments (`--deny-namespaces`, `--namespaces` , `--prometheus-instance-selector` , `prometheus-instance-namespaces`, ...) to exclude the namespaces/instances which are already catered by the platform monitoring stack. But many times, folks would not even notice that they are breaking something.

As explained before, the [ControllerRef](https://github.com/kubernetes/design-proposals-archive/blob/acc25e14ca83dfda4f66d8cb1f1b491f26e78ffe/api-machinery/controller-ref.md) proposal doesn't exactly address this problem and there's still an issue with the operator and the resources living in different namespaces.

After some research (thanks @machine424!), we've identified a potential solution already implemented by the [zalando/postgres-operator](https://github.com/zalando/postgres-operator). When an operator is configured with a specific "controller id" value, it will only reconcile the resources for which the "controller id" annotation matches the operator's value. Conversely if the operator isn't configured with a "controller id", it will skip all resources that have a "controller id" annotation . More information [here](https://github.com/zalando/postgres-operator/blob/master/docs/administrator.md#operators-with-defined-ownership-of-certain-postgres-clusters).

This sounds like a reasonable and simple approach.

**Comment by danielmellado** [comment]
Hi @simonpasquier for taking the time to resurrect this. I'd like to bring it back as well and start discussing it around. Should I use just this thread or would you like me to create a new one?

**Comment by simonpasquier** [comment]
I'd advise to start a proposal doc in `Documentation/proposals` describing the problem and the suggested addition. This issue is a bit bloated IMHO.

**Comment by danielmellado** [comment]
Totally agree, I'll prepare a document and put it there, thanks!

**Comment by simonpasquier** [comment]
#6319 implemented the controller-id proposal. While it's a bit different than the original idea discussed in this issue, I think that we can close it.
