### ISSUE TITLE
service|pod monitor do not follow prometheus labeling conventions for namespace and pod

### ISSUE THREAD

**Issue by benmathews** [prometheus-operator/prometheus-operator#4415]
Prometheus-operator generates configuration that names labels differently than Prometheus. This makes it difficult to have a mixed environment with some annotation scrapes and some from monitors. Dashboards don't work consistently.

Yes, I could change my kubernetes-pods to conform to prometheus-operator. But that would result in all our dashboards needing to be updated and any imported from grafana.com needing to be modified.

From [Prometheus](https://github.com/prometheus/prometheus/blob/main/documentation/examples/prometheus-kubernetes.yml#L293)

```
  - job_name: "kubernetes-pods"
...
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
```

Generated

```
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
```

**Environment**

* Prometheus Operator version:

    `quay.io/prometheus-operator/prometheus-operator:v0.50.0`

* Kubernetes version information:

    `v1.21.5`

* Kubernetes cluster kind:

    Hand installed

**Anything else we need to know?**:

I can make this change easily enough. Before I do so I'd like to understand why there is the deviation in the first place.

**Comment by paulfantom** [comment]
Label `namespace` and `pod` were chosen in prometheus-operator for convenience. Prometheus itself does not have any convention as to how they should be named and what you linked to is just an example of how things can be configured, not necessarily how they have to be configured.

**Comment by benmathews** [comment]
I'd argue that the `kubernetes_` prefix is a convention. That is what is documented and most dashboards at grafana.com assume users follow it. There are exceptions of course. Linkerd charts use `namespace` but that is a self-contained ecosystem where they specify the prometheus job and provide dashboards.  Choosing differently IMO only causes frustration with the project by making grafana.com dashboards not work and a mixed environment of annotations and servicemonitor not work.

This reduces my enthusiasm for using Service and PodMonitor a lot.

**Comment by simonpasquier** [comment]
@benmathews the opposite would be true for all the people using alerts and dashboards from github.com/prometheus-operator/kube-prometheus and github.com/kubernetes-monitoring/kubernetes-mixin :)
We could back in the Git history to understand which pattern came first but AFAIR the operator has always used labels without the `kubernetes_` prefix.

**Comment by paulfantom** [comment]
The `kubernetes_namespace` syntax was introduced in https://github.com/prometheus/prometheus/pull/1225 (prometheus 0.17.0) and was always treated as an example and not a convention or a best practice. Later this was copied as is into a prometheus helm chart (which was created after the operator) without looking at any consequence of breaking existing workflows and thus we are having a split. To add even more to the confusion, even different parts of prometheus codebase use `namespace` and not `kubernetes_namespace` in other places: https://github.com/prometheus/prometheus/blob/main/documentation/prometheus-mixin/config.libsonnet#L24

As Simon said, the operator always used the convention of `namespace` and not `kubernetes_namespace` and due to that, all related projects use this convention (monitoring mixins, kube-state-metrics, even grafana in its mixins is using `namespace`).

If anything I am more inclined to change that prometheus example to align it with other parts of prometheus codebase and with other projects in the existing ecosystem.

**Comment by paulfantom** [comment]
@benmathews Thank you for bringing this to our attention. Prometheus example was changed to use `namespace` as a convention. I also opened [a PR in prometheus helm chart](https://github.com/prometheus-community/helm-charts/pull/1520) to propagate that guideline.

Since the guidelines between prometheus and prometheus-operator are aligned now, I am closing this issue.

Community projects are urged to switch to using `namespace` label instead of `kubernetes_namespace` for better integration between tools, and for conformance to kubernetes instrumentation guidelines.
