### ISSUE TITLE
Pushgateway Support

### ISSUE THREAD

**Issue by edenkoveshi** [prometheus-operator/prometheus-operator#4423]
Pushgateway support in the Prometheus operator.
The idea is to deploy a pushgateway image (as a pod or as a prometheus sidecar container?) automatically, and another nice feature would be to automatically set up a PodMonitor for every Job/CronJon (with label selectors) with the relevant job path so Prometheus could automatically scrape metrics from Jobs
I'm not new to either Prometheus,Kubernetes or the Prometheus operator but I'm still learning it's code, so I would like to know whether or not it is a wanted feature. If so I could try and give a go at this.

**Comment by simonpasquier** [comment]
My gut feeling is that it would be best served by an independent operator. The Prometheus operator's focus is Prometheus, Alertmanager and Thanos Ruler and it's already a lot for us to maintain :)

**Comment by edenkoveshi** [comment]
To me it really feels like it belongs here as it is a part of the Prometheus system.
If another controller is the problem then it can be implemented within the Prometheus CR assuming we go for a sidecar (it also makes sense in a way and does have some pros to it), though I do think it should be handled in a different controller to make this independent of Prometheus controller and vice versa.

**Comment by simonpasquier** [comment]
Happy to hear what other @prometheus-operator/prometheus-operator-reviewers think but personally I'm leaning towards a dedicated operator (e.g. pushgateway-operator). It could definitely exist under the prometheus-operator organization though.

**Comment by PhilipGough** [comment]
Agree with @simonpasquier that this would fit best as a dedicated operator. There were already some discussions on the community meeting regarding the the potential of splitting out alertmanager as a dedicated operator so adding more overhead to this particular project seems like a step in the wrong direction.

**Comment by paulfantom** [comment]
From what I see from this issue, the potential pushgateway operator would need to solve two things:
1) manage pushgateway (pgw) deployment and operations
2) provide an easy way to gather metrics from applications running as Jobs

For me, the first part is fairly simple as pushgateway (pgw) is just an application handling incoming traffic and exposing it for prometheus consumption. There are not many things to tweak around here and the deployment is quite simple ([example](https://github.com/thaum-xyz/ankhmorpork/tree/master/apps/monitoring/manifests/pushgateway)). The connection of pgw with prometheus is also fairly easy when using prometheus-operator and can be done with one simple ServiceMonitor ([example](https://github.com/thaum-xyz/ankhmorpork/blob/master/apps/monitoring/manifests/pushgateway/serviceMonitor.yaml)).

The second part is completely depending on the application itself as the application needs to know about pgw URL and send/push (not expose!) data. This means the only common thing for each Job is the pgw URL. So the only premise for the operator here would be to inject a static pgw url string into a Job pod (potentially as an environment variable).

With that I don't see what is the added value of pushgateway operator or why would people use it. PGW itself can be shipped with few manifests files and there is no complex, changing, runtime configuration that would need to be managed.

---

> automatically set up a PodMonitor for every Job/CronJon

Usually PodMonitor is not a good candidate for monitoring applications running as Jobs due to the time it takes for bootstraping PodMonitor vs Job runtime. Basically with PodMonitor, you may miss 100% of metrics from applications running as Job.

> If another controller is the problem then it can be implemented within the Prometheus CR assuming we go for a sidecar

PGW doesn't need to run as prometheus sidecar as it doesn't have any tight coupling to prometheus itself. PGW is a separate component that prometheus just happens to scrape. As such its potential configuration options should not go into Prometheus CRD.

**Comment by paulfantom** [comment]
I am closing this as @edenkoveshi created a project that fits their needs and others have extensive explanation on pgw usage in https://github.com/prometheus-operator/prometheus-operator/issues/4423#issuecomment-981513973. Please reopen if you think this issue is still relevant.

---

> I will write tests but I would also appreciate your help with this if you choose to take and maintain 

Bear in mind that we also struggle with current resources to keep prometheus-operator projects up and running. I highly recommend joining our Contributor Office Hours if you want to chat about your project and its potential cooperation with prometheus-operator. Here is the agenda with all the necessary info: https://docs.google.com/document/d/1-fjJmzrwRpKmSPHtXN5u6VZnn39M28KqyQGBEJsqUOk/edit#
