### ISSUE TITLE
No default described for endpoint path

### ISSUE THREAD

**Issue by abentley** [prometheus-operator/prometheus-operator#4874]
**What happened?**
I looked at the docs and I couldn't find out which path ServiceMonitor used by default

**Did you expect to see something different?**
I expected to see a default

**How to reproduce it (as minimally and precisely as possible)**:
https://prometheus-operator.dev/docs/operator/api/#endpoint

**Environment**
N/A
* Prometheus Operator version:
N/A

* Kubernetes version information:
N/A

* Kubernetes cluster kind:
N/A

* Manifests:
N/A

* Prometheus Operator Logs:
N/A

**Anything else we need to know?**: I assume it's `/metrics`, but there's nothing authoritative that I can find.

**Comment by slashpai** [comment]
metrics path is not a required field for Endpoint since operator let prometheus set the default. It will use the default `/metrics`. But if you need to set a different path you can use `path` field in [Endpoint](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#endpoint)

**Comment by slashpai** [comment]
@simonpasquier May be we should set default metric path using openapi to avoid confusion. wdyt?

**Comment by simonpasquier** [comment]
I wouldn't set a defaut value in the OpenAPI spec because it would create friction if Prometheus changes its behavior (very unlikely though). 
But it's worth adding a comment [here](https://github.com/prometheus-operator/prometheus-operator/blob/708ea77c900806616466116ce07ddd215e3870a1/pkg/apis/monitoring/v1/types.go#L1137) to explain that it will fallback to the Prometheus default value when empty.
