### ISSUE TITLE
Lack of de-duplication of prometheus replicas generates overlap in metrics

### ISSUE THREAD

**Issue by spacegaucho** [prometheus-operator/prometheus-operator#5274]
**What happened?**
Prometheus replicas metrics are (seemingly) randomly overlapping. In some cases triggers alert-manager.

<details>

![image](https://user-images.githubusercontent.com/15604339/211629705-0505b31d-41c6-4461-94e7-fe924c0fc910.png)

![image](https://user-images.githubusercontent.com/15604339/211629769-03ce5c85-5b07-4396-81a5-0779827aec2e.png)

</details>

**Did you expect to see something different?**
Expected to see only one set of metrics at a time.

**How to reproduce it (as minimally and precisely as possible)**:
Setup the prometheus operator with 2 replicas. Execute a query in grafana with a `sum() by (prometheus_replica)`, look for overlaps.

**Environment**

* Prometheus Operator version:

    `quay.io/prometheus-operator/prometheus-operator:v0.47.0`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.2", GitCommit:"9d142434e3af351a628bffee3939e64c681afa4d", GitTreeState:"clean", BuildDate:"2022-01-19T17:29:16Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

kubeadm

* Manifests:

Replicas is set to 2.

* Prometheus Operator Logs:

N/A

**Anything else we need to know?**:

**Comment by JoaoBraveCoding** [comment]
Disclaimer: I'm not a maintainer 
If I understand correctly this is the expected behaviour. Both Prometheus replicas will scrape the same set of targets, if we then query each of them this will show some overlapping data as they will report the same data, depending if they were able to scrape the target or not.
You should deploy Thanos querier in front of the two Prometheus replicas and redirect Grafana to that, Thanos querier will perform deduplication and then give you a consistent response.

**Comment by spacegaucho** [comment]
this ended up being related to our own infrastructure. thanks for your input @JoaoBraveCoding
