### ISSUE TITLE
Minor UX eyesore in prometheus /targets page when using ScrapeConfig CR.

### ISSUE THREAD

**Issue by paulfantom** [prometheus-operator/prometheus-operator#5974]
**What happened?**

Applied ScrapeConfig to a cluster and got the following in prometheus:

<img width="326" alt="Screenshot 2023-10-07 at 11 32 58" src="https://github.com/prometheus-operator/prometheus-operator/assets/3531758/1d714bd0-f727-46b2-8a29-e2f6670b4990">

**Did you expect to see something different?**

Yes, I would expect coherent naming scheme and not a mix.

**How to reproduce it (as minimally and precisely as possible)**:

Apply any scrape config to a cluster.

**Environment**

* Prometheus Operator version:

```
v0.67.1
```

**Anything else we need to know?**:

I can easily fix this and send a PR. However I am raising this as an issue as I am not sure if using name `scrapeconfig` instead of `scrapeConfig` was a conscious design choice.

**Comment by slashpai** [comment]
Not sure if this was by design but I would confirm with @xiu

**Comment by xiu** [comment]
It's not 😅 I actually noticed this last week. People might already be relying on it though, I'd be fine changing it since we are still in alpha with a big warning in the release notes.

**Comment by simonpasquier** [comment]
I'm ok with fixing/breaking it.

**Comment by ArthurSens** [comment]
@perylemke, is this an issue that looks doable to you?

I'm still looking for code pointers, but there should be a method in `pkg/prometheus/prom_cfg.go` that generates the configuration from ServiceMonitors, PodMonitors, ScrapeConfigs, etc.

The problem here is we loop over ScrapeConfigs when generating the configuration, but we don't append the loop variable to the end like we do with ServiceMonitors, PodMonitors and Probes (notice how in the issue description Pawel is showing a `0` as suffix to everything, but for the ScrapeConfig)

**Comment by perylemke** [comment]
@ArthurSens,

I will see this issue.

**Comment by ArthurSens** [comment]
> @ArthurSens,
> 
> I will see this issue.

Reading the issue again, I'm completely wrong!!!! The inconsistency is that we should be using camelCase for SScrapeConfig 😬

**Comment by perylemke** [comment]
PR Open -> https://github.com/prometheus-operator/prometheus-operator/pull/6124
