### ISSUE TITLE
Cluster.label breaking if alertmanagers have different names

### ISSUE THREAD

**Issue by viennaa** [prometheus-operator/prometheus-operator#6158]
**What happened?**
We recently upgraded the alertmanager from v0.23.0 to v0.26.0 and our cluster stopped settling gossip (any version below v0.26.0 should have the problem).
The cluster label was set differently on each alertmanager, since they have different names.
These were the arguments the operator generated and attached to AM:
```
--cluster.label=prometheus-alertmanager/am-az-1
--cluster.label=prometheus-alertmanager/am-az-2
```

**Did you expect to see something different?**
It wasn't explicitly mentioned as breaking so a non communicating cluster was not expected.

**How to reproduce it (as minimally and precisely as possible)**:
Take two dedicated clusters, deploy an alertmanager on each, cluster them and name them differently:
* am-az-1
* am-az-2

**Environment**

* Prometheus Operator version: `0.70.0 / 2023-11-30`

* Kubernetes version information: `v1.28.2`

**Anything else we need to know?**:

The code itself implies that this might be an issue, apparently no one has run into it yet - or never reported it. Normally the names of the alertmanagers would be the same across clusters I suppose, however there might be others with the same issue.

Would you be willing to take a PR with the respective change to configure `cluster.label`?

**Comment by simonpasquier** [comment]
First of all, sorry that you had a bad upgrade experience: it wasn't definitely intentional from our side.

https://github.com/prometheus-operator/prometheus-operator/pull/5945 is the PR that introduced the change which should have been highlighted more prominently in the v0.69.0 changelog. FWIW the goal of the PR was to join unrelated Alertmanager pods running in the same cluster when IP addresses are recycled too frequently (e.g. it was a real issue).

To be clear, you're using `.spec.additionalPeers` to form the Alertmanager cluster across different kube clusters?

> Would you be willing to take a PR with the respective change to configure cluster.label?

Sure, I'd go with something like:

````
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: am-az-1
spec:
  clusterLabel: am-az
````

**Comment by viennaa** [comment]
All good, we managed it with letting the operator think it is not having a `v0.26.0` alertmanager to spec. However for future releases it would be great, to have it configurable.

Yes we're using `.spec.additionalPeers` to add the AMs to distinct clusters vice versa.

Going for the PR then.
