### ISSUE TITLE
PR working on any Scrape Config SD

### ISSUE THREAD

**Issue by dongjiang1989** [prometheus-operator/prometheus-operator#6458]
### Component(s)

ScrapeConfig

### What is missing? Please describe.

ref: https://github.com/prometheus-operator/prometheus-operator/pull/6327#issuecomment-2029540213

Since [scrape config is part of GSoc](https://github.com/prometheus-operator/community/blob/main/mentoring/gsoc/2024/project_ideas.md#extending-scrapeconfig-surface) there are many PRs related to that as well so based on whichever gets merged first others will get merge conflict.

### Describe alternatives you've considered.

- [x] #6327 
- [ ] #6346 

Merge code in reply order.

## Environment
Kubernetes Version:
Prometheus-Operator Version:

**Comment by dongjiang1989** [comment]
#6327

**Comment by dongjiang1989** [comment]
#6346

**Comment by slashpai** [comment]
@dongjiang1989 I meant incase if you are working on a ScrapeConfig SD config log a github issue with that SD name so that everyone will know you are working on it. This is to avoid duplicated efforts since there can be PRs from GSoc candidates as well 

Since both Kuma and Eureka SDs are merged now I am closing this one

**Comment by dongjiang1989** [comment]
Thanks.
