### ISSUE TITLE
Prometheus: Thanos sidecar is created with wrong Thanos version

### ISSUE THREAD

**Issue by marevers** [prometheus-operator/prometheus-operator#6601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description
When creating a Prometheus instance, the `spec.thanos.version` property is seemingly now ignored. The Thanos sidecar is deployed with the newest Thanos version, rather than the specified one.

## Steps to Reproduce
On a Prometheus object, use a Thanos specification like so - v0.34.1 is the previous version whereas v0.35.0
```
...
spec:
...
  thanos:
    version: v0.34.1
    objectStorageConfig:
      key: thanosconfig
      name: storage-config
...
```

## Expected Result
The Thanos sidecar should be using the specified version of v0.34.1

## Actual Result
The Thanos sidecar is deployed with the newest upstream version v0.35.0.

### Prometheus Operator Version

```shell
0.73.2
```

### Kubernetes Version

```yaml
v1.29.4
```

### Kubernetes Cluster Type

AKS

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### prometheus-operator log output

```shell
No log output relevant in this case.
```

**Comment by ArthurSens** [comment]
To deploy a different sidecar version, you need to specify its image instead of the field `version`.

The field `version` is used to inform the operator in case you have an image that we can't tell which version it represents. E.g.:

```yaml
spec:
  thanos:
    image: mycustomregistry/thanos:latest ## What version is latest?
    version: v0.25.0
```

The operator needs to know the Thanos version because some features are only available on newer versions, and validation needs to happen before writing the sidecar configuration based on those versions.

Reading the [ThanosSpec documentation](https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.ThanosSpec), I agree this isn't very clear. Let's improve that!

**Comment by marevers** [comment]
In that case I would assume the behavior has changed, because I have never used the spec.thanos.image field but rather only the version field. So it used to control more than just information towards the operator.

At any rate, I have added the image property in addition to the version property and now it has the correct version.
