### ISSUE TITLE
Exclude irrelevant certs/tls secrets watch in monitoring namespace

### ISSUE THREAD

**Issue by qx121** [prometheus-operator/prometheus-operator#6610]
### What is missing? Please describe.

Prometheus operator seems to watch and manage all secrets in monitoring namespace. There are other types of secrets(e.g. IPS/certs/etc) that are irrelevant to prometheus stack. Is it possible to make an include/exclude list for prometheus-operator such that it makes fewer list secret API call to kube-api-server?

## Environment
Kubernetes Version:
Prometheus-Operator Version:

**Comment by simonpasquier** [comment]
You can start the operator with `-secret-field-selector`

**Comment by pbxqdown** [comment]
@simonpasquier thanks. I think having a selector would be the correct direction for this issue. The argument is a field-selector, wondering whether we have label/annotation selector?

Also would like to know more details about how the secret selector is being used. Does monitoring components such as prometheus/alertmanager watch the secret change and update it accordingly? Thank you!

**Comment by simonpasquier** [comment]
context about why we have  a field selector: https://github.com/prometheus-operator/prometheus-operator/pull/3355

> Does monitoring components such as prometheus/alertmanager watch the secret change and update it accordingly? 

The operator needs to react on secret changes. Watching on all secrets in the namespace is the simplest solution. Having a label selector put us at risk of excluding noteworthy secrets.

What's exactly your concern here?

**Comment by pbxqdown** [comment]
We would like to reduce calls to api-server, it is also from performance perspective similar to #3355 
In our stack, not all secrets in monitoring namespace are managed by prometheus-operator. IPS are injected by other controller, certs are managed by other components as well.

It would be good to have a label-selector since it provides larger flexibility. I have free cycle to help with implementation if needed.

But if it is not trivial work, maybe we can try field-selector as well. IPS has kubernetes.io/dockerconfigjson type, so we can use field selector to exclude IPS. Wondering whether prometheus-operator manages any IPS?

**Comment by simonpasquier** [comment]
What is IPS?

I'd be ok adding a label selector argument for secrets like we have the field selector.

**Comment by pbxqdown** [comment]
it is image-pull-secret, usually injected from external party.
It would be great if label selector can be added, I can create a PR if you would like to.

**Comment by simonpasquier** [comment]
sure go ahead.

**Comment by pbxqdown** [comment]
Great, this is the PR: #6731
