### ISSUE TITLE
How to Access Prometheus/Alertmanager/ServiceMonitor CR Statuses

### ISSUE THREAD

**Issue by alecmerdler** [prometheus-operator/prometheus-operator#887]
**What did you do?**
Documentation says that the Prometheus Operator publishes CR status via its HTTP API. Tried to understand the code here: https://github.com/coreos/prometheus-operator/blob/master/pkg/api/api.go#L96.

<kubectl-proxy-url>/api/v1/proxy/namespaces/default/services/prometheus-operated:9090/apis/monitoring.coreos.com/v1/namespaces/default/prometheuses/my-prom/status

**What did you expect to see?**
JSON status 

**What did you see instead? Under which circumstances?**
HTTP 404

**Environment**
Linux

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.4+coreos.0", GitCommit:"4292f9682595afddbb4f8b1483673449c74f9619", GitTreeState:"clean", BuildDate:"2017-11-21T17:22:25Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

Tectonic installer v1.8.4

* Manifests:

n/a

* Prometheus Operator Logs:

n/a

**Comment by brancz** [comment]
We defined these objects a while back, but never actually implemented writing them back into the custom resource. What we did initially was implement the API ourselves, as TPRs were not supposed to get sub resources, but since, CRDs are now getting them we have decided not to proceed with that strategy as building the Prometheus Operator as a fully aggregated API is a big task.

We should either wait for sub resources to land (targeted alpha for 1.10) or write back the status (not a huge fan of this, as we're loosing optimistic concurrency control over the status, but in the end it shouldn't be too problematic).

**Comment by alecmerdler** [comment]
The [etcd Operator](https://github.com/coreos/etcd-operator) along with many other proprietary operators publish their status block, which is extremely helpful. I would like to see this added before Kubernetes v1.10.

**Comment by alecmerdler** [comment]
@brancz Are there any plans to write out to the `status` block for the Prometheus Operator's custom resources?

**Comment by brancz** [comment]
With real subresource support in CRDs now, I'm happy to have this added, but with current priorities I don't see this being added anytime soon.

**Comment by paulfantom** [comment]
Closing in favor of #3335
