### ISSUE TITLE
[Helm] Grafana dashboard doesnt show Scheduler and Controller Manager status

### ISSUE THREAD

**Issue by kyledakid** [prometheus-operator/prometheus-operator#907]
**What did you do?**
helm install prometheus-operator
helm install kube-prometheus

**What did you expect to see?**
Grafana dashboard should show the status of Scheduler and Controller Manager (just like we did in hack/cluster-monitoring/minikube-deploy)

**What did you see instead? Under which circumstances?**
The graphs for Scheduler and Controller Manager is showing "NA"

**Environment**

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-11-29T22:43:34Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

I use Minikube

* Manifests:

```
helm/kube-prometheus
```

**Comment by gianrubio** [comment]
Indeed is a bug, as soon I have time I'll fix that.

**Comment by brancz** [comment]
I'm not sure how much time we should invest in this, as minikube is switching it's default bootstrapper to be kubeadm, so minikube will be the same as kubeadm setups soon.

**Comment by zerda** [comment]
I have done some research with this issue, It's not about minikube or kubeadm.

Grafana is querying with `up{job="kube-controller-manager"}`, while the job name is `kube-prometheus-exporter-kube-controller-manager` in Prometheus. 

The root cause is `ServiceMonitor.jobLabel` set to chart fullname. Same issue also exists in `exporter-kube-scheduler`, `exporter-kubelets`, `exporter-kubernetes`, `exporter-node`.

I'm prefer the jobLabel sticked with `contrib/kube-prometheus/manifests` spec to the chart fullname. If it's ok to you @gianrubio, I can make a PR.

**Comment by gianrubio** [comment]
I'll be glad to accept a PR to fix this issue + labeling, just in case all the rules are generated by https://github.com/coreos/prometheus-operator/blob/master/helm/hack/sync_kube_prometheus.py so please fix the script before changing the rules.

**Comment by stonefury** [comment]
I'm on .17, and using k8s deployed on aws using kops.

I run:

hack/cluster-monitoring/deploy

But controllers and scheduler has an empty chart.

**Comment by lilic** [comment]
Closing as helm was moved out of this repo and is now in the Prometheus community org.
